---
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
        always_run: true
    
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
        always_run: true
        
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        always_run: true
        args:
          - --statistics
          - --config=pyproject.toml
        
      - id: bandit
        name: bandit
        entry: poetry run bandit
        language: system
        types: [python]
        always_run: true
        args:
          - -c
          - pyproject.toml
          - --recursive
          - --verbose
          - src
        
      - id: poetry
        name: poetry
        entry: >
          bash -c '
            poetry update;
            git diff --quiet poetry.lock ||
            (echo "Atualize o poetry.lock com o comando poetry update!" && exit 1)
          '
        language: system
        types: [python]
        always_run: true
